# Generated by Django 4.0.6 on 2022-07-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='horario',
            new_name='horario_func',
        ),
    ]
